name: di
description: A prototype of Dependency Injection framework. 
version: 0.0.3
author: "Vojta Jina <vojta.jina@gmail.com>"
homepage: https://github.com/vojtajina/dart-di

dev_dependencies:
  unittest: any
